//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApplication.AppFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public int LessonId { get; set; }
        public string LessonName { get; set; }
        public int TeacherId { get; set; }
    
        public virtual Teacher Teacher { get; set; }
    }
}
